### PR TITLE
Focus name when creating note from blueprint

### LINKED ISSUE #27: Note name not focused when creating from blueprint
**Describe the bug**
Unlike Obsidian's `Create new note` command, when creating a note with `Blueprint: Create new note from blueprint`, the note's file name isn't focused. Instead, nothing is focused, requiring the user to manually focus something.

**To Reproduce**
1. Open command palette
2. Select `Blueprint: Create new note from blueprint`
3. Nothing is focused

**Expected behavior**
The note's file name should be focused, allowing the user to immediately begin typing a new name for the note.

### PR DESCRIPTION
**Pull request by madx**
Fixes #27

### CODE REVIEW

File: src/commands.ts [hunk 1]
```diff
@@ -61,8 +61,12 @@ async function createNoteFromBlueprintInFolder(app: App, folderPath: string) {
   const mostRecentLeaf = app.workspace.getMostRecentLeaf()
 
   if (mostRecentLeaf) {
-    mostRecentLeaf.openFile(createdNote)
+    await mostRecentLeaf.openFile(createdNote)
```
Comment (madx) [inline src/commands.ts:64]: Thanks for that one, made me notice that my linter was not running properly!

File: src/commands.ts [hunk 2]
```diff
@@ -61,8 +61,12 @@ async function createNoteFromBlueprintInFolder(app: App, folderPath: string) {
...
     await app.workspace.revealLeaf(mostRecentLeaf)
+
+    mostRecentLeaf.setEphemeralState({
+      rename: "all"
+    })
```
Comment (madx) [inline src/commands.ts:69]: I didn't expect this to be that simple! Thanks
